const {
  PROJECT_ID,
  API_KEY,
  DATABASE_ID,
  USER_COLLECTION_ID,
  CREATOR_COLLECTION_ID,
  POST_COLLECTION_ID,
  CREATOR_IMAGE_PUBLIC_BUCKET_ID: IMAGE_ID,
  PUBLIC_ENDPOINT: ENDPOINT,
} = process.env;
